version: '3'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql://gk_admin:WYnAG9!qzhfx7hDatJcs@gatekeeper-db/gatekeeper_db
  #   networks:
  #     - gatekeeper-network

  gatekeeper-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gk_admin
      POSTGRES_PASSWORD: WYnAG9!qzhfx7hDatJcs
      POSTGRES_DB: gatekeeper_db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - gatekeeper-network

  gatekeeper-pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: gk_admin@data-amazon.com
      PGADMIN_DEFAULT_PASSWORD: mB!2pBNnyffE@8*W*C-8
    depends_on:
      - gatekeeper-db
    networks:
      - gatekeeper-network

volumes:
  db-data:

networks:
  gatekeeper-network:
    driver: bridge
