version: '3'

services:
  nginx-proxy:
    build: ./infrastructure/nginx/
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./infrastructure/nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=gatekeeper:9092
    ports:
      - "80:80"
      - "9000"
      - "9001"
    depends_on:
      - minio
      - tusd
      - gatekeeper
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
    networks:
      - gatekeeper_gatekeeper-network

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network
