version: '3'

services:
  gatekeeper-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gk_admin
      POSTGRES_PASSWORD: WYnAG9!qzhfx7hDatJcs
      POSTGRES_DB: gatekeeper_db
    ports:
      - 5432:5432
    volumes:
      - ../db-data:/var/lib/postgresql/data
    networks:
      - gatekeeper_gatekeeper-network

  gatekeeper-pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: gk_admin@data-amazon.com
      PGADMIN_DEFAULT_PASSWORD: mB!2pBNnyffE@8*W*C-8
    depends_on:
      - gatekeeper-db
    networks:
      - gatekeeper_gatekeeper-network

volumes:
  db-data:

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network

