version: '3'

x-logging: &logging
  driver: json-file
  options:
    max-size: "20m"
    max-file: "10"

services:
  gatekeeper-db:
    image: postgres:16.3
    restart: always
    logging: *logging
    container_name: datamap_gatekeeper_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ${ENV_FILE_PATH}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - gatekeeper_gatekeeper-network

  gatekeeper-pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    logging: *logging
    container_name: datamap_pgadmin
    env_file:
      - ${ENV_FILE_PATH}
    ports:
      - 5050:5050
    volumes:
      - ./infrastructure/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - gatekeeper-db
    networks:
      - gatekeeper_gatekeeper-network

volumes:
  database:
    driver: local
    driver_opts:
      device: ${DATABASE_DOCKER_VOLUME}
      o: bind
      type: local

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network

