version: '3'

services:
  wiremock_test_integration:
    image: wiremock/wiremock:3.3.1
    container_name: datamap_wiremock_test_integration
    ports:
      - "8083:8080"
    volumes:
      - ./tests/integration/wiremock/mappings:/home/wiremock/mappings:ro
      - ./tests/integration/wiremock/__files:/home/wiremock/__files:ro
    command: ["--global-response-templating", "--verbose"]
    networks:
      - gatekeeper_integration-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  gatekeeper_integration-test-network:
    driver: bridge
    name: gatekeeper_integration-test-network
