version: '3'

services:
  gatekeeper:
    build: .
    image: gatekeeper
    container_name: datamap_gatekeeper
    restart: always
    env_file:
      - ${ENV_FILE_PATH}
    ports: 
      - '9092:9092'
    networks:
      - gatekeeper_gatekeeper-network

  minio:
    image: minio/minio:RELEASE.2024-03-21T23-13-43Z
    command: server /storage --console-address ":9001"
    container_name: datamap_min_io
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ${ENV_FILE_PATH}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        - gatekeeper_gatekeeper-network
    hostname: minio
    volumes:
      - "../data-storage:/storage/"
  
  tusd:
    image: tusproject/tusd:v2.4
    container_name: datamap_tusd
    ports: 
      - "1080:1080"
    env_file:
      - ${ENV_FILE_PATH}
    command: -port 1080 -s3-bucket datamap -s3-endpoint http://minio:9000 -cors-allow-headers X-User-Id
    depends_on: 
      - minio
    networks:
      - gatekeeper_gatekeeper-network

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network
