version: '3'

services:
  nginx-proxy:
    build: ./infrastructure/nginx/
    image: nginx
    container_name: datamap_nginx
    restart: always
    volumes:
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ${ENV_FILE_PATH}
    ports:
      - "80:80"
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - gatekeeper_gatekeeper-network

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network
