version: '3'

services:
  gatekeeper-db:
    image: postgres:16.3
    restart: always
    container_name: datamap_gatekeeper_db
    env_file:
      - ${ENV_FILE_PATH}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - gatekeeper_gatekeeper-network

  gatekeeper-pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    container_name: datamap_pgadmin
    env_file:
      - ${ENV_FILE_PATH}
    ports:
      - 5050:5050
    volumes:
      - ./infrastructure/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - gatekeeper-db
    networks:
      - gatekeeper_gatekeeper-network

volumes:
  database:
    driver: local
    driver_opts:
      device: ${DATABASE_DOCKER_VOLUME}
      o: bind
      type: local

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network

