"""Create users and casbin RBAC model and add owner to dataset

Revision ID: 16be24c0533c
Revises: 5b7072136d5c
Create Date: 2023-08-08 00:49:19.176455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16be24c0533c'
down_revision = '5b7072136d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_provider',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider_id')
    )
    op.create_table('user_roles_association',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_table('casbin_rule')
    op.add_column('datasets', sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'datasets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'owner_id')
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='casbin_rule_pkey')
    )
    op.drop_table('user_roles_association')
    op.drop_table('user_provider')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('providers')
    # ### end Alembic commands ###
