"""Add provider ref

Revision ID: 1b93975ea3ea
Revises: 67dae46d5bc1
Create Date: 2023-08-10 18:07:44.781984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b93975ea3ea'
down_revision = '67dae46d5bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('reference', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'reference')
    # ### end Alembic commands ###
