"""Add unique constraint in ds version

Revision ID: 25a8f93fb344
Revises: ea1a0c6c42dd
Create Date: 2024-05-22 22:28:10.623569

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '25a8f93fb344'
down_revision: Union[str, None] = 'ea1a0c6c42dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_dataset_versions_name_dataset_id', 'dataset_versions', ['name', 'dataset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_dataset_versions_name_dataset_id', 'dataset_versions', type_='unique')
    # ### end Alembic commands ###
