"""Increase format column size in data_files table

Revision ID: increase_format_column_size
Revises: 76b576d1fa02
Create Date: 2024-10-07 23:58:26.202449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "increase_format_column_size"
down_revision: Union[str, None] = "76b576d1fa02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_files",
        "format",
        existing_type=sa.String(length=64),
        type_=sa.String(length=512),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_files",
        "format",
        existing_type=sa.String(length=512),
        type_=sa.String(length=64),
        existing_nullable=True
    )
    # ### end Alembic commands ### 
