"""add metadata extraction tables

Revision ID: a4458e0c5350
Revises: c3h4i5j6k7l8
Create Date: 2026-02-26 22:10:10.040262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4458e0c5350'
down_revision: Union[str, None] = 'c3h4i5j6k7l8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_jobs',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='extractionstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_file_id'], ['data_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_jobs_data_file_id', 'extraction_jobs', ['data_file_id'], unique=False)
    op.create_index('idx_extraction_jobs_status', 'extraction_jobs', ['status'], unique=False)
    op.create_table('file_metadata',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('sample_file_path', sa.String(length=2048), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=False),
    sa.Column('llm_provider', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['data_file_id'], ['data_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_file_id', name='uc_file_metadata_data_file_id')
    )
    op.create_index('idx_file_metadata_data_file_id', 'file_metadata', ['data_file_id'], unique=False)
    op.create_table('column_metadata',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_metadata_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('dtype', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('std_value', sa.Float(), nullable=True),
    sa.Column('null_count', sa.BigInteger(), nullable=True),
    sa.Column('sample_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_column_metadata_file_metadata_id', 'column_metadata', ['file_metadata_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_column_metadata_file_metadata_id', table_name='column_metadata')
    op.drop_table('column_metadata')
    op.drop_index('idx_file_metadata_data_file_id', table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_index('idx_extraction_jobs_status', table_name='extraction_jobs')
    op.drop_index('idx_extraction_jobs_data_file_id', table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    sa.Enum(name='extractionstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
