"""Create casbin table

Revision ID: 6b1d362e7799
Revises: 921a4077da90
Create Date: 2023-08-08 01:07:33.185026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1d362e7799'
down_revision = '921a4077da90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='casbin_rule_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
