"""Initial migration

Revision ID: 8263437b31e9
Revises: 
Create Date: 2023-07-03 19:47:28.270066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8263437b31e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
