"""Update tenancy models

Revision ID: 8b70fc6c2dcb
Revises: 1a67325e7c53
Create Date: 2024-02-13 19:56:01.592747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b70fc6c2dcb'
down_revision = '1a67325e7c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenancies',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_index('idx_users_tenancies_user_id', table_name='users_tenancies')
    op.create_foreign_key(None, 'users_tenancies', 'tenancies', ['tenancy'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_tenancies', type_='foreignkey')
    op.create_index('idx_users_tenancies_user_id', 'users_tenancies', ['user_id'], unique=False)
    op.drop_table('tenancies')
    # ### end Alembic commands ###
