"""Fix relationship

Revision ID: 8bd38b992ce3
Revises: ac17eca489af
Create Date: 2024-04-08 22:28:49.355023

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8bd38b992ce3"
down_revision = "ac17eca489af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_files", "created_by", existing_type=postgresql.UUID(), nullable=True
    )
    op.alter_column(
        "dataset_versions", "dataset_id", existing_type=postgresql.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset_versions",
        "dataset_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "data_files", "created_by", existing_type=postgresql.UUID(), nullable=False
    )
    # ### end Alembic commands ###
