"""Create users email index

Revision ID: 921a4077da90
Revises: 6d9d9bb338c5
Create Date: 2023-08-08 00:51:02.615947

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "921a4077da90"
down_revision = "6d9d9bb338c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_users_email", "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_email", table_name="users")
    # ### end Alembic commands ###
