"""Add index to provider ref and name

Revision ID: f88aba31677a
Revises: 1b93975ea3ea
Create Date: 2023-08-10 18:08:50.144508

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "f88aba31677a"
down_revision = "1b93975ea3ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_providers_name", "providers", ["name"], unique=False)
    op.create_index("idx_providers_reference", "providers", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_providers_reference", table_name="providers")
    op.drop_index("idx_providers_name", table_name="providers")
    # ### end Alembic commands ###
